package rules.backward;

import com.ftn.sbnz.train.model.facts.TrainStatus;
import com.ftn.sbnz.train.model.facts.Infrastructure;
import com.ftn.sbnz.train.model.facts.MovementAuthority;
import com.ftn.sbnz.train.model.facts.Car;
import com.ftn.sbnz.train.model.facts.Coupling;
import com.ftn.sbnz.train.model.enums.DoorStatus;
import com.ftn.sbnz.train.model.enums.BrakeTestStatus;
import com.ftn.sbnz.train.model.enums.CouplingStatus;
import com.ftn.sbnz.train.model.enums.SifaStatus;
import com.ftn.sbnz.train.model.enums.InteractionType;
import com.ftn.sbnz.train.model.events.Warning;
import com.ftn.sbnz.train.model.events.DriverActivity;
import com.ftn.sbnz.train.model.facts.RouteNode;

query doorsLockedOnCar(Car car)
    (
        Car(this == car, doorStatus == DoorStatus.LOCKED, nextCar == null)
    )
    or
    (
        Car(this == car, doorStatus == DoorStatus.LOCKED, $next: nextCar != null)
        and doorsLockedOnCar($next;)
    )
end


query brakeTestPassedOnAllCars(Car car)
    (
        Car(this == car, brakeTest == BrakeTestStatus.PASSED, nextCar == null)
    )
    or
    (
        Car(this == car, brakeTest == BrakeTestStatus.PASSED, $next: nextCar != null)
        and brakeTestPassedOnAllCars($next;)
    )
end

query maReceived()
    $t: TrainStatus($p: position)
    MovementAuthority(eoa > $p)
end

query doorsLockedAll()
    $loco: Car(locomotive == true)
    doorsLockedOnCar($loco;)
end

query brakeSystemReady()
    TrainStatus(brakePressure >= 4.8, compressorOperational == true)
    $loco: Car(locomotive == true)
    brakeTestPassedOnAllCars($loco;)
end

query driverReady()
    TrainStatus(sifaStatus == SifaStatus.OPERATIONAL)
    DriverActivity(type == InteractionType.SIFA_RESET)
end

query safeToDepart()
    maReceived()
    doorsLockedAll()
    brakeSystemReady()
    driverReady()
end


query isSafeRouteTree(RouteNode node)
    (
        RouteNode(this == node, clear == true, left == null, right == null)
    )
    or
    (
        RouteNode(this == node, clear == true, $l: left != null)
        and isSafeRouteTree($l;)
    )
    or
    (
        RouteNode(this == node, clear == true, $r: right != null)
        and isSafeRouteTree($r;)
    )
end

