package rules.accumulate;

import com.ftn.sbnz.train.model.facts.TrainStatus;
import com.ftn.sbnz.train.model.facts.Infrastructure;
import com.ftn.sbnz.train.model.facts.Car;
import com.ftn.sbnz.train.model.facts.GradientSegment;
import com.ftn.sbnz.train.model.enums.WarningType;
import com.ftn.sbnz.train.model.events.Warning;


rule "Rule 10: Accumulate average gradient for next 1000m"
    no-loop true
    salience 93
    when
        $t: TrainStatus($pos: position)
        $infra: Infrastructure($currentGrad: gradient)
        $avg: Number(doubleValue != $currentGrad)
            from accumulate(
                $g: GradientSegment(endPosition >= $pos,
                                    startPosition < ($pos + 1000),
                                    $val: gradient),
                average($val)
            )
    then
        modify($infra) { setGradient($avg.doubleValue()) }
        System.out.println(String.format(
            "[Rule 10] Avg gradient %.2f%% over next 1000m from pos=%.1f",
            $avg.doubleValue(), $pos));
end
